-- AlterTable
ALTER TABLE "Contest" ALTER COLUMN "icpcRegion" DROP NOT NULL,
ALTER COLUMN "country" DROP NOT NULL,
ALTER COLUMN "city" DROP NOT NULL,
ALTER COLUMN "season" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Problem" ALTER COLUMN "type" SET NOT NULL,
ALTER COLUMN "type" SET DATA TYPE TEXT;
