version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
